"""empty message

Revision ID: 419d7aee43ca
Revises: 
Create Date: 2017-11-20 13:59:41.772146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '419d7aee43ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caterory',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_title', sa.String(length=30), nullable=True),
    sa.Column('category_description', sa.String(length=1000), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.add_column('recipe', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('recipe', sa.Column('recipe_description', sa.String(length=1000), nullable=True))
    op.add_column('recipe', sa.Column('recipe_title', sa.String(length=30), nullable=True))
    op.drop_column('recipe', 'description')
    op.drop_column('recipe', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('title', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('recipe', sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_column('recipe', 'recipe_title')
    op.drop_column('recipe', 'recipe_description')
    op.drop_column('recipe', 'category_id')
    op.drop_table('caterory')
    # ### end Alembic commands ###
