"""empty message

Revision ID: def84b6fc742
Revises: 
Create Date: 2017-11-21 00:03:43.627145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'def84b6fc742'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('category_description', sa.String(length=1000), nullable=True))
    op.add_column('category', sa.Column('category_id', sa.String(length=100), nullable=False))
    op.add_column('category', sa.Column('category_title', sa.String(length=30), nullable=True))
    op.drop_column('category', 'recipe_title')
    op.drop_column('category', 'recipe_id')
    op.drop_column('category', 'recipe_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('recipe_description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('category', sa.Column('recipe_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('category', sa.Column('recipe_title', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_column('category', 'category_title')
    op.drop_column('category', 'category_id')
    op.drop_column('category', 'category_description')
    # ### end Alembic commands ###
