"""empty message

Revision ID: f3bf710714c1
Revises: 
Create Date: 2018-02-15 17:48:49.870852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3bf710714c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_id', sa.String(length=100), nullable=False),
    sa.Column('category_title', sa.String(length=30), nullable=True),
    sa.Column('category_description', sa.String(length=1000), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('category_date_stamp', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('user',
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('user_date_stamp', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('Recipes',
    sa.Column('recipe_id', sa.String(length=100), nullable=False),
    sa.Column('recipe_title', sa.String(length=30), nullable=True),
    sa.Column('recipe_description', sa.String(length=1000), nullable=True),
    sa.Column('category_id', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('recipe_date_stamp', sa.String(length=30), nullable=True),
    sa.Column('recipe_public_status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.PrimaryKeyConstraint('recipe_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Recipes')
    op.drop_table('user')
    op.drop_table('category')
    # ### end Alembic commands ###
